image:
  file: .gitpod/Dockerfile

ports:
  # Laravel server
  - port: 8000
    onOpen: open-preview
  # MySQL server
  - port: 3306
    onOpen: ignore

tasks:
  - name: Setup DB
    init: >
      gp await-port 3306 &&
      mysql -u root -e "create database laravel"
    openMode: split-right
  - name: Setup site
    init:  >
      cp .env.example .env &&
      sed -i "s|APP_URL=|APP_URL=${GITPOD_WORKSPACE_URL}|g" .env &&
      sed -i "s|APP_URL=https://|APP_URL=https://8000-|g" .env
      composer install &&
      php artisan key:generate      
    openMode: split-right
  - name: Serve site
    command: php -S 0.0.0.0:8000 -t public
    openMode: split-right
  - name: Compile Assets
    init: npm install
    command: npm run watch
    openMode: split-right
    